# Generated by Django 4.2.10 on 2024-02-20 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_officer_is_active'),
        ('account', '0008_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provinceadmin',
            name='admin',
        ),
        migrations.AddField(
            model_name='provinceadmin',
            name='admins',
            field=models.ManyToManyField(limit_choices_to={'role': 1}, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='provinceadmin',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.province'),
        ),
    ]
