# Generated by Django 4.2.10 on 2024-02-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_provinceadmin_admin_provinceadmin_admins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provinceadmin',
            old_name='admins',
            new_name='admin',
        ),
    ]
