# Generated by Django 4.2.10 on 2024-03-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_admins_provinceadmin_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ADMIN'), (2, 'AGENT'), (3, 'SUPERADMIN')], null=True),
        ),
    ]
