# Generated by Django 4.2.10 on 2024-03-27 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceadmin',
            name='admin',
            field=models.ManyToManyField(limit_choices_to=models.Q(('role', 1), ('role', 3), _connector='OR'), to=settings.AUTH_USER_MODEL),
        ),
    ]
