# Generated by Django 4.2.10 on 2024-02-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_delete_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
