# Generated by Django 4.2.10 on 2024-03-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='phone',
        ),
    ]
