# Generated by Django 4.2.10 on 2024-03-28 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_officer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='designation',
            field=models.CharField(max_length=200),
        ),
    ]
